

title: Aleck Vi
author: Aleck Vi
email: av@defiteck.com
description: > # this means to ignore newlines until "baseurl:"
  My journey as a blockchain developer, decentralized finance (DeFi),
  dApps, web3, crypto, business development, growth hacking, remote work,
  and life after coronavirus!
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
